Unit tests for current
FHIR/fhir-package-loader pull request #34
Opened 2024-07-25 14:41 UTC by KaelynJefferson

This PR includes:
- unit tests for current folder: BuildDotFhirDotOrgClient

To test:
- npm/jest

Related Issue: n/a

2024-08-07 16:56 UTC, cmoesel requested changes
This is off to a great start! I've made a few suggestions/requests, but I think you're really close!

2024-08-07 16:56 UTC, cmoesel commented on test/current/BuildDotFhirDotOrgClient.test.ts
> +              loggerSpy.reset();
I'm not sure what happened, but I noticed that there's a lot of extra indenting in this file (see lines 20+ below for another example). I thought that `prettier` would complain about this, but it doesn't. Still... I'd like us to stick to 2-space indenting. The easiest way to do that is to open the file in VS Code, then press `<Command>-<Shift>-P`, type "Reindent Lines", and select it. Then save your file.

2024-08-07 16:56 UTC, cmoesel commented on test/current/BuildDotFhirDotOrgClient.test.ts
> +          });
As far as I can tell, this is the same test as the one above it (just with a few less expectations). I don't think we need the redundant test -- so I'd suggest you delete this one and update the previous one's description to say: `'should download the most current package from the main branch when no branch given'`. That way it's clear that it covers this case as well.

2024-08-07 16:56 UTC, cmoesel commented on test/current/BuildDotFhirDotOrgClient.test.ts
> +            expect(loggerSpy.getLastMessage('info')).toBe('Attempting to download sushi-test#current from https://build.fhir.org/ig/sushi/sushi-test/branches/master/package.tgz');
I think it would be good to test this all the way through to the download. So I'd suggest updating the axios mock to respond to `https://build.fhir.org/ig/sushi/sushi-test/branches/master/package.tgz` with data as well. And perhaps instead of using `zipfile` as the data, make it something more specific, like `sushi-test master zip file`.  I'd say this goes for any test that should result in a successful download: let's test it all the way through.

2024-08-07 16:56 UTC, cmoesel commented on test/current/BuildDotFhirDotOrgClient.test.ts
> +          });
This is another test that looks like it is the same test as the one on 114 above. Maybe we should use this US Core one for this tricky test since it's already set up well for this in the `qas.json`, but update the first test (on line 114) to use the simpler use case (a package with main branch and only one entry in qas).

2024-08-07 16:56 UTC, cmoesel commented on test/current/BuildDotFhirDotOrgClient.test.ts
> +          });
I feel like maybe this should reject like the other ones above -- because the end result is the same: it can't download the package. I think the registries reject when they attempt to download something that's not there, right? If so, then it would be good to be consistent. But if I'm wrong, and they also return undefined, then let's discuss.

2024-08-07 16:56 UTC, cmoesel commented on test/current/BuildDotFhirDotOrgClient.test.ts
> +          });
I think this can be removed, as it seems that it is testing the same thing as the previous test on line 233.

2024-08-07 16:56 UTC, cmoesel commented on test/current/BuildDotFhirDotOrgClient.test.ts
> +          });
This one is also the same as the others (if you just look at what it's actually doing in the test). I think it is good to have a separate test for this use case (multiple versions), but I think it should be different than the test for the simpler use case. Since `sushi-test` `testbranch` is already setup for the multi-version test, I think it would be good to update the test on line 233 to use a different branch name that doesn't have multiple versions.

2024-08-07 16:56 UTC, cmoesel commented on test/current/BuildDotFhirDotOrgClient.test.ts
> +                }
I don't think these are used in the tests, are they? If not, you can probably remove them.

2024-08-07 16:56 UTC, cmoesel commented on test/current/BuildDotFhirDotOrgClient.test.ts
> +      });
Is returning `undefined` consistent with the registry classes? Or would it be more consistent for the function to throw an error so the promise is rejected? If the latter, can you update the `BuildDotFhirDotOrgClient` to throw in this case and update the tests acccordingly?

2024-08-07 16:56 UTC, cmoesel commented on test/current/BuildDotFhirDotOrgClient.test.ts
> +        });
Can we setup the test fixture so that these use different dates? That way we're sure it's doing the right thing and associating the right date with the right package?

2024-08-07 16:56 UTC, cmoesel commented on test/current/BuildDotFhirDotOrgClient.test.ts
> +            });
I think this, and perhaps some other parts of this (?), is not used in the tests and can be removed.

2024-08-07 16:56 UTC, cmoesel commented on test/current/BuildDotFhirDotOrgClient.test.ts
> +                // is the not found case needed with new impl?
Sure -- let's add a test for when something is not found, which I think would more likely be a response with a HTTP 404 error. The bit in the fixture below would more likely represent an unexpected error during download, which we can also go ahead and test for too.

2024-08-07 22:53 UTC, KaelynJefferson commented on test/current/BuildDotFhirDotOrgClient.test.ts
> +          });
Will replace these, but keep the 3 tests expecting 'undefined' for getCurrentBuildDate

2024-08-07 23:13 UTC, KaelynJefferson commented on test/current/BuildDotFhirDotOrgClient.test.ts
> +                }
these are used with the two tests below (for the second axios get), so will keep for now!

2024-08-22 17:14 UTC, cmoesel approved these changes
This all looks good! Thank you!

2024-08-22 17:14 UTC, merged